In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab

In [5]:
df_chungcu = pd.read_csv('../data/test/dataset_chungcu.csv')
df_chungcu.head(5)

,DiaChi,Quan,TinhTrangBDS,DienTich,Phongngu,TenPhanKhu,SoTang,PhongTam,Loai,GiayTo,MaCanHo,TinhTrangNoiThat,HuongCuaChinh,HuongBanCong,DacDiem,Gia,USD,log_price
0,"Đường Nguyễn Văn Quỳ, Phường Phú Thuận, Quận 7...",Quận 7,Đã bàn giao,62.0,2.0,NaN,NaN,2.0,Chung cư,Đã có sổ,NaN,NaN,NaN,NaN,NaN,2.000000e+09,83333.0,11.330600
1,"Đường Nguyễn Văn Linh, Phường Tân Thuận Tây, Q...",Quận 7,Đã bàn giao,95.0,3.0,NaN,NaN,2.0,Chung cư,Đang chờ sổ,NaN,Nội thất cao cấp,NaN,NaN,Căn góc,5.300000e+09,220833.0,12.305162
2,"Đường Võ Văn Kiệt, Phường An Lạc, Quận Bình Tâ...",Quận Bình Tân,Chưa bàn giao,75.0,2.0,2,5.0,2.0,Chung cư,Giấy tờ khác,17,NaN,Đông Nam,Đông Nam,NaN,2.580000e+09,107500.0,11.585246
3,"108, Đường Hồng Hà, Phường 2, Quận Tân Bình, T...",Quận Tân Bình,Đã bàn giao,70.0,1.0,A,7.0,1.0,Chung cư,Đang chờ sổ,BPA - 0712,Nội thất cao cấp,Đông Nam,Tây Bắc,NaN,4.000000e+09,166667.0,12.023753
4,"Đường Hậu Giang, Phường 11, Quận 6, Tp Hồ Chí ...",Quận 6,Đã bàn giao,83.0,2.0,NaN,NaN,2.0,Chung cư,Đã có sổ,NaN,Nội thất cao cấp,Tây Bắc,NaN,NaN,2.950000e+09,122917.0,11.719265

In [6]:
df_chungcu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24019 entries, 0 to 24018
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DiaChi            24019 non-null  object
 1   Quan              24019 non-null  object
 2   TinhTrangBDS      24017 non-null  object
 3   DienTich          24019 non-null  float64
 4   Phongngu          24019 non-null  float64
 5   TenPhanKhu        6865 non-null   object
 6   SoTang            6529 non-null   float64
 7   PhongTam          24019 non-null  float64
 8   Loai              24019 non-null  object
 9   GiayTo            18286 non-null  object
 10  MaCanHo           3281 non-null   object
 11  TinhTrangNoiThat  12420 non-null  object
 12  HuongCuaChinh     9167 non-null   object
 13  HuongBanCong      8502 non-null   object
 14  DacDiem           5431 non-null   object
 15  Gia               24019 non-null  float64
 16  USD               24019 non-null  float64
 17  log_price         24019 non-null  float64
dtypes: float64(7), object(11)
memory usage: 3.3+ MB

In [7]:
df_chungcu['HuongBanCong'].value_counts()

HuongBanCong
Đông Nam    1939
Tây Nam     1118
Tây Bắc     1092
Đông Bắc    1046
Đông         982
Bắc          935
Tây          712
Nam          678
Name: count, dtype: int64

In [20]:
df_chungcu['Quan'].value_counts()

Quan
Quận 7              2914
Quận 9              2777
Quận 8              2422
Quận Bình Tân       2165
Quận Thủ Đức        1988
Quận 2              1807
Quận Tân Phú        1462
Huyện Nhà Bè        1091
Quận Bình Thạnh      956
Quận 12              888
Quận Tân Bình        786
Huyện Bình Chánh     727
Quận 6               683
Quận Phú Nhuận       641
Quận Gò Vấp          608
Quận 10              474
Quận 4               406
Huyện Hóc Môn        346
Quận 5               343
Quận 1               318
Quận 3               108
Quận 11               97
Huyện Củ Chi          12
Name: count, dtype: int64